-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 20:51:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `TipoDocumento` VARCHAR(45) NOT NULL,
  `Documento` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `NombreAcudiente` VARCHAR(45) NULL,
  `DocumentoAcudiente` VARCHAR(45) NULL,
  `FechaNacimiento` DATE NULL,
  `Telefono` VARCHAR(45) NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Cursos` (
  `idCurso` INT NOT NULL,
  `NombreCurso` VARCHAR(45) NOT NULL,
  `IdJornada` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Asignaturas` (
  `idAsignaturas` INT NOT NULL,
  `NombreAsignatura` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `idNivel` INT NOT NULL,
  `Creditos` INT NULL,
  PRIMARY KEY (`idAsignaturas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Matriculas` (
  `idMatriculas` INT NOT NULL AUTO_INCREMENT,
  `idCurso` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`idMatriculas`),
  INDEX `fk_Matriculas_Alumnos_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `idCurso_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `idAlumnos`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `proyecto`.`Alumnos` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `proyecto`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Calificaciones` (
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `anio` INT NOT NULL,
  `idAsignatura` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Calificaciones_Cursos1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Calificaciones_Cursos1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `proyecto`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificaciones_idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `proyecto`.`Matriculas` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Roles` (
  `idRol` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Docente` (
  `idDocente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Documento` VARCHAR(45) NOT NULL,
  `TipoDocumento` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idDocente`),
  INDEX `fk_Docente_Roles1_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_Roles1`
    FOREIGN KEY (`idRol`)
    REFERENCES `proyecto`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`AsignacionAcademica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`AsignacionAcademica` (
  `Cursos_idCurso` INT NOT NULL,
  `Asignaturas_idAsignaturas` INT NOT NULL,
  `idDocente` INT NOT NULL,
  `anio` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`Cursos_idCurso`, `Asignaturas_idAsignaturas`),
  INDEX `fk_Cursos_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_idAsignaturas` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Asignaturas_Cursos1_idx` (`Cursos_idCurso` ASC) VISIBLE,
  INDEX `idDocente_idx` (`idDocente` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Asignaturas_Cursos1`
    FOREIGN KEY (`Cursos_idCurso`)
    REFERENCES `proyecto`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_idAsignaturas`)
    REFERENCES `proyecto`.`Asignaturas` (`idAsignaturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDocente`
    FOREIGN KEY (`idDocente`)
    REFERENCES `proyecto`.`Docente` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Jornadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Jornadas` (
  `idJornada` INT NOT NULL,
  `Jornadas` VARCHAR(45) NULL,
  PRIMARY KEY (`idJornada`),
  CONSTRAINT `fk_Jornadas_Cursos1`
    FOREIGN KEY (`idJornada`)
    REFERENCES `proyecto`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
